### ISSUE TITLE
Architektura na przykładzie rejestracji

### ISSUE THREAD

**Issue by jstarczewski** [Softwaret/kpdf#12]
Routing.register() - tutaj interpretujemy call, czy posiada odpowiedni token (not yet) i przekazujemy parametry ciała do kontrolera
RegisterController - walidacja danych pod katem nullowalności, poprawności względem możliwych checków, miejsce w którym zwracamy odpowiedni response (wszystko co serializowalne - error, czy response)
RegisterInteractor - czytany jak formularz szereg możliwych operacji dla danego use case np zarejestrowanie i autoryzacja użytkownika, sprawdzenie czy istnieje
UserRepository - tego jeszcze nie ma, tutaj cacheowanie danych w pamięci aby nie strzelać selectami co chwila tylko jakoś moralnie zarządzać danymi
UserService - serwis wykonujący selecty na bazie danych pls z użyciem DSL Exposed API (nie jakieś DAO) 
Oczywiście jakieś utile aby sobie upraszczać itp.
No primo wszystko na interfejsach i jak najdalej od tego Ktora

Jan co o tym sądzisz ???
<b>Oczywiście to w bardzo dużym uproszczeniu, bo start small i aby najpierw działało a takie pierdoły jak hashowanie haseł 15 razy, sprytne tokeny JWT, walidacja hasła pod względem trudnych literek i znaczków to później</b>

**Comment by JanStoltman** [comment]
@jstarczewski  Chyba rozpykane po moim MR? Chyba że masz uwagi?
